---
- hosts: localhost
  become: true
  tasks:
    - name: Install required packages on Debian/Ubuntu
      apt:
        name: "{{ item }}"
        update_cache: true
      with_items:
        - curl
        - git
        - unzip
        - python3-pip
      when: ansible_os_family == "Debian"
    - name: Install required packages on RedHat
      yum:
        name: "{{ item }}"
        update_cache: true
      with_items:
        - curl
        - git
        - unzip
      when: ansible_os_family == "RedHat"
    - name: check if AWS CLI is installed
      command: which aws
      register: aws_installed
      failed_when: aws_installed.rc not in [0,1]
      changed_when: false
      become: false
    - debug:
        msg: "{{ aws_installed }}"
    - name: Install AWS CLI
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -u awscliv2.zip && ./aws/install --update
      #args:
      #  creates: /usr/local/bin/aws
      when: aws_installed.rc != 0
    - name: Install helm
      shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && PATH=$PATH:/usr/local/bin ./get_helm.sh
      args:
        creates: /usr/local/bin/helm
    - name: Install kubeclt
      shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod 755 kubectl && mv kubectl /usr/bin
      args:
        creates: /usr/bin/kubectl
